In [1]:
import numpy as np

In [7]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
np.ones((4,8)).dtype

dtype('float64')

In [12]:
np.zeros((4,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.random.randint(2,10, (2,5))

array([[7, 5, 9, 6, 3],
       [9, 2, 5, 2, 7]])

In [26]:
np.random.random((7,6))

array([[0.76469576, 0.60309709, 0.33027558, 0.14238618, 0.51626675,
        0.32262086],
       [0.97376024, 0.54945755, 0.41825196, 0.80729825, 0.46081784,
        0.47978996],
       [0.46904276, 0.62426174, 0.41291266, 0.2088534 , 0.98606059,
        0.93462243],
       [0.41485311, 0.24324162, 0.52404425, 0.32634307, 0.50372071,
        0.89911383],
       [0.49940023, 0.87082796, 0.8070367 , 0.62684609, 0.62072036,
        0.60512224],
       [0.78283283, 0.66146455, 0.9008666 , 0.47122864, 0.23617816,
        0.7563905 ],
       [0.90615283, 0.76619923, 0.37091443, 0.04118091, 0.81131173,
        0.58632539]])

In [34]:
np.random.seed(21)
np.random.random()

0.04872488080912729

## metrics and vectors 
- 1 dimentional arrays are vector
- < 1 dimentional arrays called matrixes